{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-ripple/1.7.2/material-ripple-1.7.2.module",
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-release.aar",
          "url": "material-ripple-android-1.7.2.aar",
          "size": 96135,
          "sha512": "5cd80cf8c814f0bba4eb315cfc4323e3abd2890c4590bfd8d6f05bf210f86e55b0ddfe62b26f7ccbca81039faa16931dd4b4b99cb4e37391fdd362d86d62e6fb",
          "sha256": "7aa14b51938e7c3c9b01014738441f5a1afb1fd2ca2c9ff18f265b87fe5b459c",
          "sha1": "7efef90991ca0fc115dfecbb199d55353b298e26",
          "md5": "8e6e9a9d182eeda0b271c526e219f340"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "material-ripple-release.aar",
          "url": "material-ripple-android-1.7.2.aar",
          "size": 96135,
          "sha512": "5cd80cf8c814f0bba4eb315cfc4323e3abd2890c4590bfd8d6f05bf210f86e55b0ddfe62b26f7ccbca81039faa16931dd4b4b99cb4e37391fdd362d86d62e6fb",
          "sha256": "7aa14b51938e7c3c9b01014738441f5a1afb1fd2ca2c9ff18f265b87fe5b459c",
          "sha1": "7efef90991ca0fc115dfecbb199d55353b298e26",
          "md5": "8e6e9a9d182eeda0b271c526e219f340"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "material-ripple-android-1.7.2-sources.jar",
          "url": "material-ripple-android-1.7.2-sources.jar",
          "size": 26493,
          "sha512": "cf75021625684728c83771b88735b3c52e328994c7adca1b415f16d3a433253c8775f06626aa791bfaa025a992577e661fd2645eab2fa4ad264e86352921ec52",
          "sha256": "ef8710a7152243363ce61099827c5e07618dd2911032311da38b0275cdebea4e",
          "sha1": "7850da88009864d77e29340230e91bcb270656d9",
          "md5": "fb144e81bbdee600bd3575d47e6c4d76"
        }
      ]
    }
  ]
}