{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-1.7.2-multiplatform-sources.jar",
          "url": "foundation-1.7.2-multiplatform-sources.jar",
          "size": 877835,
          "sha512": "de5eeeb135cf6960c210dca2f578d8324646eaffbe0a7eae24df9ea9066d58d268f076d33029fed6cf508e62897b81337ff7be038fa6c610b9e09c40b22ea1b3",
          "sha256": "17f483f19e9ce270e5729a58fd613dd331b4d0648525cb939100e537f611f6ea",
          "sha1": "77020f813ab807d5bf34ce1411eac4923dfa1da7",
          "md5": "cf0799b8853fab2f400345a256f9fd70"
        },
        {
          "name": "foundation-1.7.2-samples-sources.jar",
          "url": "foundation-1.7.2-samples-sources.jar",
          "size": 70960,
          "sha512": "e6915fda8c84b27f1fb4ef88ad8fecf0946b6bb5ed172c17baeec6ea1c7f178203f3e8877e6fe31c05f4b48ae924697aa34fce3e48971495e938535a707372ad",
          "sha256": "5a6b849641c2a695f3a0581b3c0580ea75330660c32a6fd60ebaf475fdfc7b3f",
          "sha1": "73cc34ad1d4dc4fd23d3af615e71abf6880c7510",
          "md5": "644d279dff3106b5f276edd15a0ec1f1"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "foundation-1.7.2-versionMetadata.json",
          "size": 181283,
          "sha512": "6c86ef2f307e4cf3ca30f04fbe89f8f70972e8b0ea1f0ee0aec8c1d10dcf29076041e7580192b993dbe07ecf158056bcd6c67b1eaaca1fa060e14f3247fc8b7d",
          "sha256": "c3b1a198fdac03d658c7a74ac873b97ec5d53b973a2023e5f9278418d76334c0",
          "sha1": "77d72e2861a7ac3a46e1d25ef9b245c73416b8fd",
          "md5": "f262086c5704e0882775a3f4110fe245"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-metadata-1.7.2.jar",
          "url": "foundation-1.7.2.jar",
          "size": 178687,
          "sha512": "9c9bcd66cfed89541b6cefdeee2a7709fcb1a536d1e18ee21f7aabfb55ee13096524d73f51449ad18c614eba260aa9de3e5179834a7770858a8ad5afa0f20072",
          "sha256": "f5e57be8b1c242edb70c2cae3f87813d68da566aec877ca4f1323195d2d92fdc",
          "sha1": "64cefe0761276bfb3b4f59918cdda7e7c872b842",
          "md5": "ddf8b041131eefd66ac3992b22b383f8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-kotlin-1.7.2-sources.jar",
          "url": "foundation-1.7.2-sources.jar",
          "size": 772664,
          "sha512": "ebd19990dc4ee490d21bb701952d078711c8b6f54a27ff2c83793fd1e3df74e09d0479ade2cb1e384bff9e278a6d51efe14a131d69c849e91608ddaabc0b0f97",
          "sha256": "93241fe61a1855e218ea62e5242832151397ba3b7547a52deaf3df7330a33cfb",
          "sha1": "3dd22eb2a4871de2df9126fbc3982ba369003337",
          "md5": "6c6e2574f6a4fce93a0060bd309653e6"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.7.2/foundation-android-1.7.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.7.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.7.2/foundation-android-1.7.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.7.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.7.2/foundation-android-1.7.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.7.2"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-jvmstubs/1.7.2/foundation-jvmstubs-1.7.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-jvmstubs",
        "version": "1.7.2"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-jvmstubs/1.7.2/foundation-jvmstubs-1.7.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-jvmstubs",
        "version": "1.7.2"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-jvmstubs/1.7.2/foundation-jvmstubs-1.7.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-jvmstubs",
        "version": "1.7.2"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-linuxx64stubs/1.7.2/foundation-linuxx64stubs-1.7.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-linuxx64stubs",
        "version": "1.7.2"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-linuxx64stubs/1.7.2/foundation-linuxx64stubs-1.7.2.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-linuxx64stubs",
        "version": "1.7.2"
      }
    }
  ]
}