{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.compiler",
    "module": "compiler",
    "version": "1.5.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.5.15"
          },
          "reason": "compiler is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-1.5.15.jar",
          "url": "compiler-1.5.15.jar",
          "size": 1181762,
          "sha512": "f357a5a09466bad8e39da545ae5d0df0b75e4e035119505c9031a04ec5722ab2aa457c61a6f2da863628958c52624fd5a17309a8ab36d5fb2b85b354ca4c34ba",
          "sha256": "5d4c7f6875cd0214838101a4375656f0f962258bd81d29f996f233c241b53fba",
          "sha1": "6a7ab324cf74a7e7010f99e37beb95ec8540e094",
          "md5": "79cd9696c1907c7002c871b88666842e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.5.15"
          },
          "reason": "compiler is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-1.5.15.jar",
          "url": "compiler-1.5.15.jar",
          "size": 1181762,
          "sha512": "f357a5a09466bad8e39da545ae5d0df0b75e4e035119505c9031a04ec5722ab2aa457c61a6f2da863628958c52624fd5a17309a8ab36d5fb2b85b354ca4c34ba",
          "sha256": "5d4c7f6875cd0214838101a4375656f0f962258bd81d29f996f233c241b53fba",
          "sha1": "6a7ab324cf74a7e7010f99e37beb95ec8540e094",
          "md5": "79cd9696c1907c7002c871b88666842e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.5.15"
          },
          "reason": "compiler is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-1.5.15-sources.jar",
          "url": "compiler-1.5.15-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}