{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-tooling-preview/1.7.2/ui-tooling-preview-1.7.2.module",
    "group": "androidx.compose.ui",
    "module": "ui-tooling-preview",
    "version": "1.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-release.aar",
          "url": "ui-tooling-preview-android-1.7.2.aar",
          "size": 17210,
          "sha512": "16385fb8ed04690efcec3ea4744426aa4eef8aa7d729f952344df4401aabd63b9adc2a6f365cdd591fa389b8a024d6ec3b4cf31c10f2dba6077c6ec15b6b90a2",
          "sha256": "959409b04ab8d77864335c7fe9cb761d3ef8a045bc46cff08b02013f5a954b4e",
          "sha1": "ff32ad37ced8828f0847dbd1c8931d0595a17949",
          "md5": "3205950b65d83765b7beceed3090305c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-release.aar",
          "url": "ui-tooling-preview-android-1.7.2.aar",
          "size": 17210,
          "sha512": "16385fb8ed04690efcec3ea4744426aa4eef8aa7d729f952344df4401aabd63b9adc2a6f365cdd591fa389b8a024d6ec3b4cf31c10f2dba6077c6ec15b6b90a2",
          "sha256": "959409b04ab8d77864335c7fe9cb761d3ef8a045bc46cff08b02013f5a954b4e",
          "sha1": "ff32ad37ced8828f0847dbd1c8931d0595a17949",
          "md5": "3205950b65d83765b7beceed3090305c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.2"
          },
          "reason": "ui-tooling-preview is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-android-1.7.2-sources.jar",
          "url": "ui-tooling-preview-android-1.7.2-sources.jar",
          "size": 11464,
          "sha512": "23ad2a05e3b97168678704fd92d8e1b45b94ecf18279a02c6ea39b4875373abe92ac93d512baf5f4b9c0a8e279d44ce928addb764964e8ac9d9c2e946c8cdb79",
          "sha256": "f76b360ee60d9e4524ae43b3ccdfb11537493baa240d71e741c429d2a03a16a3",
          "sha1": "4e724872e09ef641dd678dcf8bf607f556a76d0c",
          "md5": "244c74d876d28432d18534446d81898f"
        }
      ]
    }
  ]
}