{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-icons-extended/1.7.2/material-icons-extended-1.7.2.module",
    "group": "androidx.compose.material",
    "module": "material-icons-extended",
    "version": "1.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-release.aar",
          "url": "material-icons-extended-android-1.7.2.aar",
          "size": 35720998,
          "sha512": "22bcead999f8694199c4588c86f5dbf69b424cb6d8009f189d1316bc3411dedad5743f851dfc56d8b04b92d63848fc187292197f9b6e11b453400597f5f137f3",
          "sha256": "cb4abd93d9919c4a4d05b0a4978120a45723cf22434f7c814de65379e7f1c4e1",
          "sha1": "c2a39d3a0e7af884c4c41d0050695bcccbb06697",
          "md5": "b9e124282f2b60ecf5c8793aa30c8bde"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-release.aar",
          "url": "material-icons-extended-android-1.7.2.aar",
          "size": 35720998,
          "sha512": "22bcead999f8694199c4588c86f5dbf69b424cb6d8009f189d1316bc3411dedad5743f851dfc56d8b04b92d63848fc187292197f9b6e11b453400597f5f137f3",
          "sha256": "cb4abd93d9919c4a4d05b0a4978120a45723cf22434f7c814de65379e7f1c4e1",
          "sha1": "c2a39d3a0e7af884c4c41d0050695bcccbb06697",
          "md5": "b9e124282f2b60ecf5c8793aa30c8bde"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "material-icons-extended-android-1.7.2-sources.jar",
          "url": "material-icons-extended-android-1.7.2-sources.jar",
          "size": 12085941,
          "sha512": "8052018ed087abb947f6063970211a78b1ca963fc3ba045bd07cd61e5817a5a3ebc61e2214ed1b88257011e5649899dfa3ab49d51b305d2dcf9b1971fc13bab5",
          "sha256": "9b22840d9d5ec83fca54783df66640c0e2d76bb164687d654c23bcc6c02f3a96",
          "sha1": "4c74984f208526fde6a4ad0d78d00a8d33cbcce0",
          "md5": "9eb38b15d560c68fa1c277d4dbd85fe9"
        }
      ]
    }
  ]
}