{
  "formatVersion": "1.1",
  "component": {
    "group": "io.coil-kt",
    "module": "coil-gif",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.coil-kt",
          "module": "coil-base",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "coil-gif-2.6.0.aar",
          "url": "coil-gif-2.6.0.aar",
          "size": 44748,
          "sha512": "33eb95c8a445978278486775a7d971d799ec859dce1c7bc2851d0d4c8344e044b9fa7898889d0b39bbff49c6196adee141b5e3006ab3ea090cec514f8cd0fdf6",
          "sha256": "17d8c04cee12accd32ee7f10a46924a1bd84fa3d60135c37c5c2867c40edeec9",
          "sha1": "2d998bb072581875d832cb226984f0641542680c",
          "md5": "8cd188f927f7120371344275e83e07ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-base",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "coil-gif-2.6.0.aar",
          "url": "coil-gif-2.6.0.aar",
          "size": 44748,
          "sha512": "33eb95c8a445978278486775a7d971d799ec859dce1c7bc2851d0d4c8344e044b9fa7898889d0b39bbff49c6196adee141b5e3006ab3ea090cec514f8cd0fdf6",
          "sha256": "17d8c04cee12accd32ee7f10a46924a1bd84fa3d60135c37c5c2867c40edeec9",
          "sha1": "2d998bb072581875d832cb226984f0641542680c",
          "md5": "8cd188f927f7120371344275e83e07ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coil-gif-2.6.0-sources.jar",
          "url": "coil-gif-2.6.0-sources.jar",
          "size": 13445,
          "sha512": "91e5a15198848890daa49cc6cea7da538ec6121c9c501d6a5325cb64ba5779e704c6c9914b034db0930a2c41cf83b032de7e1a46b89aeae338cfc3a46c7611ae",
          "sha256": "280b05711a82adec04a67648e7a524f072a09813be950525fa1e843e5be1c96f",
          "sha1": "70f1aa6264979b45ce1d1c4b764c3ffda4ca6f1c",
          "md5": "b0d22ee46bcdf84b2128532f6c67310d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coil-gif-2.6.0-javadoc.jar",
          "url": "coil-gif-2.6.0-javadoc.jar",
          "size": 332962,
          "sha512": "9179847b222ced8d9a726b5f4baf72e75b900d3e843930962a87f30545849ca19274960b88d23fda4ba62d845624d4b2baa710647d4dc3eac6b20eb01f8c62aa",
          "sha256": "6e6c3093be782ae7eb6f89e8ad3bb0603b45676509f279d4362731d229cf045f",
          "sha1": "6732db3001849408b7b566c94eabdea9b8d1c59f",
          "md5": "9f4231574f76f185864b8f688fb90c69"
        }
      ]
    }
  ]
}
