package com.smartsales.data.crm.hub

import android.util.Log
import com.smartsales.prism.domain.crm.ClientProfileHub
import com.smartsales.prism.domain.crm.EntitySnapshot
import com.smartsales.prism.domain.crm.FocusedContext
import com.smartsales.prism.domain.crm.ProfileActivityState
import com.smartsales.prism.domain.crm.QuickContext
import com.smartsales.prism.domain.memory.EntityEntry
import com.smartsales.prism.domain.memory.EntityRepository
import com.smartsales.prism.domain.memory.MemoryEntry
import com.smartsales.prism.domain.memory.MemoryRepository
import com.smartsales.prism.domain.rl.ReinforcementLearner
import com.smartsales.prism.domain.scheduler.ScheduledTaskRepository
import com.smartsales.prism.domain.scheduler.TimelineItemModel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.flowOf
import javax.inject.Inject
import javax.inject.Singleton

/**
 * 客户档案中心 — Real Implementation
 * File Explorer Layer processing.
 */
@Singleton
class RealClientProfileHub @Inject constructor(
    private val entityRepository: EntityRepository,
    private val memoryRepository: MemoryRepository,
    private val scheduledTaskRepository: ScheduledTaskRepository,
    private val rlModule: ReinforcementLearner
) : ClientProfileHub {

    override suspend fun getQuickContext(entityIds: List<String>): QuickContext {
        val snapshots = mutableMapOf<String, EntitySnapshot>()
        val recentActivities = mutableListOf<MemoryEntry>()

        for (id in entityIds) {
            val entity = entityRepository.getById(id) ?: continue
            val lastActivity = memoryRepository.getByEntityId(id, 1).firstOrNull()
            if (lastActivity != null) {
                recentActivities.add(lastActivity)
            }
            snapshots[id] = EntitySnapshot(
                entityId = entity.entityId,
                displayName = entity.displayName,
                entityType = entity.entityType,
                lastActivity = lastActivity
            )
        }

        return QuickContext(
            entitySnapshots = snapshots,
            recentActivities = recentActivities.sortedByDescending { it.createdAt },
            suggestedNextSteps = emptyList() // Generated by LLM later
        )
    }

    override suspend fun getFocusedContext(entityId: String): FocusedContext {
        val entity = entityRepository.getById(entityId)
            ?: throw IllegalArgumentException("Entity not found: $entityId")

        val relatedContacts = if (entity.entityType.name == "ACCOUNT") {
            entityRepository.getByAccountId(entityId)
                .filter { it.entityType.name == "CONTACT" }
        } else emptyList()

        val relatedDeals = if (entity.entityType.name == "ACCOUNT") {
            entityRepository.getByAccountId(entityId)
                .filter { it.entityType.name == "DEAL" }
        } else emptyList()

        val userHabitsContext = rlModule.loadUserHabits()
        val clientHabitsContext = rlModule.loadClientHabits(listOf(entityId))
        
        // Merge them
        val habitContext = com.smartsales.prism.domain.rl.HabitContext(emptyList(), emptyList(), emptyMap())

        return FocusedContext(
            entity = entity,
            relatedContacts = relatedContacts,
            relatedDeals = relatedDeals,
            activityState = ProfileActivityState(emptyList(), emptyList()), // Async stream
            habitContext = habitContext
        )
    }

    override suspend fun observeProfileActivityState(entityId: String): Flow<ProfileActivityState> {
        val entity = entityRepository.getById(entityId)
            ?: return flowOf(ProfileActivityState(emptyList(), emptyList()))

        // Collect all IDs to observe
        val targetIds = mutableSetOf(entityId)
        if (entity.entityType.name == "ACCOUNT") {
            val contacts = entityRepository.getByAccountId(entityId)
                .filter { it.entityType.name == "CONTACT" }
            targetIds.addAll(contacts.map { it.entityId })
        }

        if (targetIds.isEmpty()) return flowOf(ProfileActivityState(emptyList(), emptyList()))

        // Create independent flows for all targets
        val memoryFlows = targetIds.map { memoryRepository.observeByEntityId(it) }
        val taskFlows = targetIds.map { scheduledTaskRepository.observeByEntityId(it) }

        // Combine all memory flows
        val combinedMemories = combine(memoryFlows) { arrays ->
            val flat = arrays.flatMap { it.toList() }
            // DISTINCT on entryId to remove duplicates if structuredJson cross-references
            val distinct = flat.distinctBy { it.entryId }
            distinct.sortedByDescending { it.createdAt }
        }

        // Combine all task flows
        val combinedTasks = combine(taskFlows) { arrays ->
            val flat = arrays.flatMap { it.toList() }
            val distinct = flat.distinctBy { it.id }
            distinct.sortedByDescending { it.startTime }
        }

        // Combine both into ProfileActivityState
        return combine(combinedMemories, combinedTasks) { memories, tasks ->
            Log.d("RealClientProfileHub", "observeProfileActivityState: emitted tasks=${tasks.size}, memories=${memories.size} for $entityId")
            ProfileActivityState(
                actionableItems = tasks,
                factualItems = memories
            )
        }
    }
}
