{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material",
    "version": "1.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "material-1.7.2-multiplatform-sources.jar",
          "url": "material-1.7.2-multiplatform-sources.jar",
          "size": 247496,
          "sha512": "01f62c8a04db1ca69b6819087d69dab194046aaab89510c03f9668edd82725399fbd3a17fae215afdb461c8f2a9436e9054aa09bacc5fcd0ef5a94f5f3c1d44f",
          "sha256": "0d4ffe7ecfafec934baec0b08375f99ebad3f13583579ae3306ee42b144da65b",
          "sha1": "3c4469efdbcf8058c8d581a981a1a980ee22c29a",
          "md5": "1b7d20cfcbcafd211b84628c4882e6a5"
        },
        {
          "name": "material-1.7.2-samples-sources.jar",
          "url": "material-1.7.2-samples-sources.jar",
          "size": 45207,
          "sha512": "a04b759ccfaba8c3cbf2d322b8799e17a04731c570c61627fa3c0d353ba8794d4a28b8c12b96100d3b5cf35e6083dce85749eff12f78b0f56c169d5f217344ce",
          "sha256": "650bfced6e90fba241db7884bf3785482f41c0ae5ce4f68a7d66039e1d16339b",
          "sha1": "6ebb29bfb19a8ee27431234559e62b4c84103b07",
          "md5": "f555171c43ba4e2c91d5c46f826a3e18"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "material-1.7.2-versionMetadata.json",
          "size": 90463,
          "sha512": "9768f1b7c41c1f72f752674bc6e5a0f6e663c2ca5df2fd62d356403266d930daf66e8d88a97cf9a423f9544c0c0f2dc79aa2eba246294a7bffb61ead87c8ab26",
          "sha256": "bae823d8b1fe80c1b0a60f9e05960b7371e985439131ef0c50834cb9ac2478c4",
          "sha1": "ae38ca719a66b98a9f38afe759ee1f01d819af08",
          "md5": "a8c87952d43a3e3f66afc7070a34cbc6"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "material-metadata-1.7.2.jar",
          "url": "material-1.7.2.jar",
          "size": 50801,
          "sha512": "bc23caa30fa9b8a1741a670e8cd850d0b719cbbf24594aacba13364718d556fee001e197482bab3201f5a5843bf3652e2bcbbdb425c05d06f88ad32a204790b7",
          "sha256": "e9028da82b72d3e1849c2d661e9f0cab57047a555f01e84e3c5efecabb3a5edd",
          "sha1": "2883933e3b6ca5051723c4861ebc848b51370f98",
          "md5": "1fd989d4203d3aad030709f30bebf0e1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "material-kotlin-1.7.2-sources.jar",
          "url": "material-1.7.2-sources.jar",
          "size": 231104,
          "sha512": "6bb52591fbd6ab5bbee7f3edf249acfaca5fbc41b40bbd889a6099fd24f5442bf64f2155de13b27d2b54f1bf5d5c1734c1e5d58bd18b3a117ee9fdbcc7f76a61",
          "sha256": "f092d4edf61090fadcba14cfe84ac7b2bb75982440e9e899bce1719a2a1e19be",
          "sha1": "fbc4d87cce022b7bd4c3fe90915732eae5b2b4e3",
          "md5": "658b221350924573e903d4c78aaf4acb"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-android/1.7.2/material-android-1.7.2.module",
        "group": "androidx.compose.material",
        "module": "material-android",
        "version": "1.7.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-android/1.7.2/material-android-1.7.2.module",
        "group": "androidx.compose.material",
        "module": "material-android",
        "version": "1.7.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-android/1.7.2/material-android-1.7.2.module",
        "group": "androidx.compose.material",
        "module": "material-android",
        "version": "1.7.2"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-jvmstubs/1.7.2/material-jvmstubs-1.7.2.module",
        "group": "androidx.compose.material",
        "module": "material-jvmstubs",
        "version": "1.7.2"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-jvmstubs/1.7.2/material-jvmstubs-1.7.2.module",
        "group": "androidx.compose.material",
        "module": "material-jvmstubs",
        "version": "1.7.2"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-jvmstubs/1.7.2/material-jvmstubs-1.7.2.module",
        "group": "androidx.compose.material",
        "module": "material-jvmstubs",
        "version": "1.7.2"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-linuxx64stubs/1.7.2/material-linuxx64stubs-1.7.2.module",
        "group": "androidx.compose.material",
        "module": "material-linuxx64stubs",
        "version": "1.7.2"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-linuxx64stubs/1.7.2/material-linuxx64stubs-1.7.2.module",
        "group": "androidx.compose.material",
        "module": "material-linuxx64stubs",
        "version": "1.7.2"
      }
    }
  ]
}