// File: data/ai-core/src/main/java/com/smartsales/data/aicore/disector/DisectorImpl.kt
// Module: :data:ai-core
// Summary: Batch planning implementation per Orchestrator-V1 Appendix A
// Author: created on 2026-01-11

package com.smartsales.data.aicore.disector

import javax.inject.Inject
import javax.inject.Singleton
import kotlin.math.floor

/**
 * DisectorImpl: deterministic batch planner implementation.
 * 
 * Implements V1 Appendix A rules for time-based batch splitting.
 * 
 * Note: audioAssetId is passthrough (not generated by Disector).
 * Per spec section 6.1: "audioAssetId must not be set by Disector"
 * means Disector receives but does not generate/modify this ID.
 */
@Singleton
class DisectorImpl @Inject constructor() : Disector {

    override fun createPlan(
        totalMs: Long,
        audioAssetId: String,
        recordingSessionId: String
    ): DisectorPlan {
        // If <= 20 minutes, no split
        if (totalMs <= TWENTY_MIN_MS) {
            return DisectorPlan(
                disectorPlanId = generatePlanId(audioAssetId, totalMs),
                audioAssetId = audioAssetId,
                recordingSessionId = recordingSessionId,
                totalMs = totalMs,
                batches = listOf(
                    DisectorBatch(
                        batchIndex = 1,
                        batchAssetId = generateBatchAssetId(audioAssetId, 1),
                        absStartMs = 0,
                        absEndMs = totalMs,
                        captureStartMs = 0,
                        captureEndMs = totalMs
                    )
                )
            )
        }

        // Split flow
        val full = floor(totalMs.toDouble() / TEN_MIN_MS).toInt()
        val remMs = totalMs % TEN_MIN_MS

        val batches = mutableListOf<DisectorBatch>()
        
        // Generate full 10-minute batches
        for (i in 0 until full) {
            val absStart = i * TEN_MIN_MS
            val absEnd = absStart + TEN_MIN_MS
            val captureStart = if (i == 0) 0L else maxOf(0, absStart - OVERLAP_MS)
            
            batches += DisectorBatch(
                batchIndex = i + 1,
                batchAssetId = generateBatchAssetId(audioAssetId, i + 1),
                absStartMs = absStart,
                absEndMs = absEnd,
                captureStartMs = captureStart,
                captureEndMs = absEnd
            )
        }

        // Handle remainder
        if (remMs < SEVEN_MIN_MS) {
            // Merge into last batch
            val last = batches.removeLast()
            batches += last.copy(
                absEndMs = totalMs,
                captureEndMs = totalMs
            )
        } else {
            // Create remainder batch
            val absStart = full * TEN_MIN_MS
            batches += DisectorBatch(
                batchIndex = full + 1,
                batchAssetId = generateBatchAssetId(audioAssetId, full + 1),
                absStartMs = absStart,
                absEndMs = totalMs,
                captureStartMs = maxOf(0, absStart - OVERLAP_MS),
                captureEndMs = totalMs
            )
        }

        // Two-pass: add post-roll overlap to all batches except last (§A.4)
        val finalBatches = batches.mapIndexed { index, batch ->
            if (index < batches.lastIndex) {
                batch.copy(captureEndMs = minOf(batch.absEndMs + OVERLAP_MS, totalMs))
            } else {
                batch
            }
        }

        return DisectorPlan(
            disectorPlanId = generatePlanId(audioAssetId, totalMs),
            audioAssetId = audioAssetId,
            recordingSessionId = recordingSessionId,
            totalMs = totalMs,
            batches = finalBatches
        )
    }

    private fun generatePlanId(audioAssetId: String, totalMs: Long): String =
        "plan_${audioAssetId}_${totalMs}_v${RULE_VERSION}"

    private fun generateBatchAssetId(audioAssetId: String, batchIndex: Int): String =
        "${audioAssetId}_b${batchIndex}"

    companion object {
        private const val TEN_MIN_MS = 600_000L
        private const val SEVEN_MIN_MS = 420_000L
        private const val TWENTY_MIN_MS = 1_200_000L
        private const val OVERLAP_MS = 10_000L
        private const val RULE_VERSION = 1
    }
}
